POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "sumeet_parmarrr",
  "name": "Sumeet Parmar",
  "password": "Sumeet_1998",
  "gender": "male",
  "location": "Baroda"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "sumeet_parmarrr",
  "password": "Sumeet_1998"
}

###
PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "sumeet_parmarrr",
  "oldPassword": "Sumeet_1998",
  "newPassword": "Sumeet"
}